name: AWS DEPLOY
# turn off deploy to AWS

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.AWS_DB_HOST }}
      DB_PW: ${{ secrets.AWS_DB_PW}}
      DB_USER: ${{ secrets.AWS_DB_USER }}
      DB_NAME: ${{ secrets.AWS_DB_NAME }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v2
        with:
            node-version: '20.14.0'
      - run: npm install -g npm@latest
      - run: npm install

      - run: |
          touch .env
          echo DB_HOST = "$DB_HOST" >> .env
          echo DB_PW = "$DB_PW" >> .env
          echo DB_USER = "$DB_USER" >> .env
          echo DB_NAME = "$DB_NAME" >> .env

      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: "ec2-52-15-111-82.us-east-2.compute.amazonaws.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/storytime-backend"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@ec2-52-15-111-82.us-east-2.compute.amazonaws.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: true
          command: |
            cd nodeapps/storytime-backend
            npm install
            sudo systemctl stop storytime-backend
            sudo cp storytime-backend.service /lib/systemd/system/storytime-backend.service
            sudo systemctl daemon-reload
            sudo systemctl start storytime-backend
